## Overview numpy

In [21]:
dados = [[1, 2, 3, 4],[5, 5, 7, 8]]

In [2]:
dados

[[1, 2, 3, 4], [5, 5, 7, 8]]

In [3]:
type(dados)

list

In [4]:
dados * 5

[[1, 2, 3, 4],
 [5, 5, 7, 8],
 [1, 2, 3, 4],
 [5, 5, 7, 8],
 [1, 2, 3, 4],
 [5, 5, 7, 8],
 [1, 2, 3, 4],
 [5, 5, 7, 8],
 [1, 2, 3, 4],
 [5, 5, 7, 8]]

In [6]:
dados[0] * 5

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [24]:
def multiplica_por_cinco(dados):
    lista2 = []
    lista3 = []

    for elemento in dados[0]:
        lista2.append(elemento * 5)
    for elemento in dados[1]:
        lista3.append(elemento * 5)

    dados = [lista2, lista3]
    return dados

In [25]:
dados

[[1, 2, 3, 4], [5, 5, 7, 8]]

In [31]:
type(dados)

list

In [26]:
multiplica_por_cinco(dados)

[[5, 10, 15, 20], [25, 25, 35, 40]]

In [27]:
def multiplica_por_cinco_agil(dados):
    
    lista2 = [elemento * 5 for elemento in dados[0]] # compreensao de lista ou list comprehension
    lista3 = [elemento * 5 for elemento in dados[1]]
    dados = [lista2, lista3]
    return dados

In [28]:
multiplica_por_cinco_agil(dados)

[[5, 10, 15, 20], [25, 25, 35, 40]]

In [29]:
import numpy as np

In [32]:
type(np.array(dados))

numpy.ndarray

In [33]:
dadosnp = np.array(dados)

In [34]:
type(dadosnp)

numpy.ndarray

In [35]:
dadosnp * 5

array([[ 5, 10, 15, 20],
       [25, 25, 35, 40]])

In [37]:
# função mágica ou magic function de tempo
# %timeit?

In [38]:
%timeit multiplica_por_cinco(dados)

2.16 µs ± 97 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [39]:
%timeit multiplica_por_cinco_agil(dados)

2.26 µs ± 125 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [40]:
%timeit dadosnp * 5

1.78 µs ± 58.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [42]:
dadosnp.shape # dimensões do array

(2, 4)

In [44]:
# np.reshape? # mudar as dimensões do array

In [45]:
dados2 = [[1, 2, 3], 
          [4, 5, 6], 
          [7, 8, 9]]

In [46]:
np.array(dados2).shape

(3, 3)

In [48]:
dadosnp = dadosnp * 5

In [49]:
dadosnp

array([[ 5, 10, 15, 20],
       [25, 25, 35, 40]])

In [50]:
dadosnp.min()

5

In [51]:
dadosnp.max()

40

In [53]:
(5+10+15+20+25+25+35+40)/8 # media

21.875

In [54]:
dadosnp.mean()

21.875

In [56]:
lista_zeros = [0]*5

In [57]:
lista_zeros

[0, 0, 0, 0, 0]

In [58]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [59]:
lista_zeros = [[0]*5, [0]*5]

In [60]:
lista_zeros

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]

In [63]:
np.zeros([2,5]) # linhas, colunas

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [65]:
np.full(10, 1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [67]:
np.full([2, 5], [1, 2, 3, 4, 5]) # shape, elementos

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [68]:
np.full?

In [71]:
dadosnp[0][1]

10

In [72]:
dadosnp

array([[ 5, 10, 15, 20],
       [25, 25, 35, 40]])

In [73]:
dadosnp[1][2]

35

In [75]:
dadosnp[1:]

array([[25, 25, 35, 40]])

In [77]:
dadosnp[:]

array([[ 5, 10, 15, 20],
       [25, 25, 35, 40]])

In [78]:
import pandas as pd

In [79]:
df_ml = pd.read_csv('dados_mercado_livre.csv')

In [80]:
df_ml.head()

zona  quartos  area  preco
0  sul      1.0  30.0    700
1  sul      2.0  90.0   1700
2  sul      1.0  30.0    600
3  sul      1.0  40.0    850
4  sul      1.0  20.0    500

In [81]:
type(df_ml)

pandas.core.frame.DataFrame

In [83]:
# df_ml.quartos

In [84]:
type(df_ml['quartos'])

pandas.core.series.Series

In [86]:
type(df_ml.values)

numpy.ndarray

In [87]:
type(df_ml['quartos'][0])

numpy.float64